#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" = "" ] || [ "${2:-}" = "" ]; then
  echo "사용법: $0 <법정동코드_전체자료.txt 경로> <출력 sql 경로>"
  exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="$2"

if [ ! -f "$INPUT_FILE" ]; then
  echo "입력 파일을 찾을 수 없습니다: $INPUT_FILE"
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<'SQL_HEADER'
-- generated by generate-master-dong-seed-sql.sh
-- source: 법정동코드 전체자료
START TRANSACTION;
SQL_HEADER

awk -F'\t' '
function trim(v) {
  gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "", v);
  return v;
}
function sql_escape(v) {
  gsub(/\047/, "\047\047", v);
  return v;
}
function ends_with_hangjeong(v) {
  return (v ~ /(동|읍|면|가|리)$/);
}
{
  code = trim($1);
  name = trim($2);
  status = trim($3);

  if (code == "" || name == "") next;
  if (status ~ /폐지/) next;
  if (length(code) != 10) next;
  if (substr(code, 9, 2) == "00") next;

  n = split(name, parts, " ");
  if (n < 2) next;

  city = parts[1];
  district = (n >= 3 ? parts[2] : parts[1]);
  dong = parts[n];

  if (!ends_with_hangjeong(dong)) next;

  city = sql_escape(city);
  district = sql_escape(district);
  dong = sql_escape(dong);

  printf "INSERT INTO service_area_master_dongs (code, city, district, dong, is_active) VALUES (\047%s\047, \047%s\047, \047%s\047, \047%s\047, TRUE) ON DUPLICATE KEY UPDATE city = VALUES(city), district = VALUES(district), dong = VALUES(dong), is_active = VALUES(is_active), updated_at = CURRENT_TIMESTAMP;\n", code, city, district, dong;
}
' "$INPUT_FILE" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" <<'SQL_FOOTER'
COMMIT;
SQL_FOOTER

echo "생성 완료: $OUTPUT_FILE"
