param(
    [Parameter(Mandatory = $true)]
    [string]$InputFile,
    [Parameter(Mandatory = $true)]
    [string]$OutputFile
)

if (-not (Test-Path $InputFile)) {
    Write-Error "입력 파일을 찾을 수 없습니다: $InputFile"
    exit 1
}

$outputDir = Split-Path -Parent $OutputFile
if ($outputDir -and -not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

$header = @(
    "-- generated by generate-master-dong-seed-sql.ps1",
    "-- source: 법정동코드 전체자료",
    "START TRANSACTION;"
)
Set-Content -Path $OutputFile -Value $header -Encoding UTF8

$lines = Get-Content -Path $InputFile -Encoding UTF8
foreach ($line in $lines) {
    if ([string]::IsNullOrWhiteSpace($line)) {
        continue
    }

    $parts = $line -split "`t"
    if ($parts.Length -lt 2) {
        continue
    }

    $code = $parts[0].Trim()
    $name = $parts[1].Trim()
    $status = if ($parts.Length -ge 3) { $parts[2].Trim() } else { "" }

    if ([string]::IsNullOrWhiteSpace($code) -or [string]::IsNullOrWhiteSpace($name)) { continue }
    if ($status -match "폐지") { continue }
    if ($code.Length -ne 10) { continue }
    if ($code.Substring(8, 2) -eq "00") { continue }

    $nameParts = $name -split " "
    if ($nameParts.Length -lt 2) { continue }

    $city = $nameParts[0]
    $district = if ($nameParts.Length -ge 3) { $nameParts[1] } else { $nameParts[0] }
    $dong = $nameParts[$nameParts.Length - 1]

    if ($dong -notmatch "(동|읍|면|가|리)$") { continue }

    $city = $city.Replace("'", "''")
    $district = $district.Replace("'", "''")
    $dong = $dong.Replace("'", "''")

    $sql = "INSERT INTO service_area_master_dongs (code, city, district, dong, is_active) VALUES ('$code', '$city', '$district', '$dong', TRUE) ON DUPLICATE KEY UPDATE city = VALUES(city), district = VALUES(district), dong = VALUES(dong), is_active = VALUES(is_active), updated_at = CURRENT_TIMESTAMP;"
    Add-Content -Path $OutputFile -Value $sql -Encoding UTF8
}

Add-Content -Path $OutputFile -Value "COMMIT;" -Encoding UTF8
Write-Host "생성 완료: $OutputFile"
